### ISSUE TITLE
No such file or directory: 'data/prior/monomer_library.csv'

### ISSUE THREAD

**Issue by shauseth** [charlesxu90/helm-gpt#1]
Traceback (most recent call last):
  File "/Users/shauseth/Desktop/helm-gpt-main/train_prior.py", line 9, in <module>
    from prior.trainer import Trainer, TrainerConfig
  File "/Users/shauseth/Desktop/helm-gpt-main/prior/trainer.py", line 16, in <module>
    from utils.helm_utils import get_validity
  File "/Users/shauseth/Desktop/helm-gpt-main/utils/helm_utils.py", line 281, in <module>
    df_monomers = pd.read_csv('data/prior/monomer_library.csv')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1024, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 618, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1618, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1878, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/prior/monomer_library.csv'

**Comment by charlesxu90** [comment]
It is added in the data folder.

**Comment by charlesxu90** [comment]
For specific application, you need to build your own monomer libraries.
