### ISSUE TITLE
Error in the training step

### ISSUE THREAD

**Issue by amin-sagar** [charlesxu90/helm-gpt#2]
Hello.
Thanks for this really awesome work.
I am trying to go through the steps of training as detailed in the README.
I think the files might have changed because I get an error as follows.
```
(helm-gpt-env) amin@BTX-CC1:~/softwares/helm-gpt$ python train_prior.py --train_data data/prior/chembl32/biotherapeutics_dict_prot.csv --valid_data data/prior/chembl32/biotherapeutics_dict_prot.csv --output_dir result_amin/prior/chembl_5.0 --n_epochs 200 --max_len 200 --batch_size 1024
Traceback (most recent call last):
  File "train_prior.py", line 113, in <module>
    main(args)
  File "train_prior.py", line 69, in main
    df_train = pd.read_csv(args.train_data)
  File "/home/amin/mambaforge/envs/helm-gpt-env/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/amin/mambaforge/envs/helm-gpt-env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/amin/mambaforge/envs/helm-gpt-env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/amin/mambaforge/envs/helm-gpt-env/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/amin/mambaforge/envs/helm-gpt-env/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 58, saw 5
```
Note, I changed the name of the file to biotherapeutics_dict_prot.csv because biotherapeutics_dict_prot_flt.csv is not in the directory.

I would be really grateful for any suggestions.
Best,
Amin.

**Comment by charlesxu90** [comment]
`data/prior/chembl32/biotherapeutics_dict_prot_flt.csv` data is added.
