### ISSUE TITLE
Error in training agent

### ISSUE THREAD

**Issue by amin-sagar** [charlesxu90/helm-gpt#3]
Thanks for resolving #2 
I can now run the first step, but the second step gives the error
```
Traceback (most recent call last):
  File "train_agent.py", line 11, in <module>
    from agent.scoring.scaffold import Scaffold
ModuleNotFoundError: No module named 'agent.scoring.scaffold'
```

Best,
Amin.

**Comment by charlesxu90** [comment]
It's deleted as not used.

**Comment by amin-sagar** [comment]
Thanks @charlesxu90 
What's the correct way of running the step 2 of the documentation in that case?

**Comment by charlesxu90** [comment]
Any bug you met after the deletion? It is a new function that I tried to implement but not completed. It should be working well when deleted it.

**Comment by amin-sagar** [comment]
Thanks @charlesxu90 
I misunderstood your last response.
After I remove 
```
from agent.scoring.scaffold import Scaffold
```
The training starts but throws an error
```
2024-07-05 08:55:19.839 | INFO     | agent.agent_trainer:train:239 - Step 10, Avg score:   0.21, permeability:  -8.60
Traceback (most recent call last):
  File "train_agent.py", line 108, in <module>
    main(args)
  File "train_agent.py", line 77, in main
    loss_type=args.loss_type, alpha=args.alpha, use_amp=not(args.no_amp))
  File "train_agent.py", line 58, in train_agent
    trainer.train()
  File "/home/amin/softwares/helm-gpt/agent/agent_trainer.py", line 224, in train
    loss, scores, agent_likelihoods, prior_likelihoods, augmented_likelihoods, scores_df = self._run_step(step)
  File "/home/amin/softwares/helm-gpt/agent/agent_trainer.py", line 192, in _run_step
    sample_idxes, agent_likelihoods = self.sample(self.agent_model, self.batch_size)  # Sample from agent
  File "/home/amin/softwares/helm-gpt/agent/agent_trainer.py", line 115, in sample
    sampled_idx = Categorical(probs=probs).sample().squeeze()
  File "/home/amin/mambaforge/envs/helm-gpt-env/lib/python3.7/site-packages/torch/distributions/categorical.py", line 66, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/amin/mambaforge/envs/helm-gpt-env/lib/python3.7/site-packages/torch/distributions/distribution.py", line 57, in __init__
    f"Expected parameter {param} "
ValueError: Expected parameter probs (Tensor of shape (8, 76)) of distribution Categorical(probs: torch.Size([8, 76])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan],
```
My exact command for launching the training of the agent is
```
python train_agent.py --prior result_amin/prior/chembl_5.0/gpt_model_final_0.349.pt --output_dir result_amin/agent/cpp/pep_perm_5.1_reinvent --batch_size 8 --n_steps 500 --sigma 60 --task permeability  --max_len 140
```

Best,
Amin

**Comment by charlesxu90** [comment]
This error comes from the small batch size. This job requries a GPU with large memory to run. Based on my trial, a batch size of 32 works. It pops up `nan` because the agent cannot learn anything from this batch size.
